"""
Markdown report writer — produces a GitHub-flavored Markdown report
suitable for pasting into a README, blog post, or issue.

Same inputs as json_report / html_report:
    results      — list of result dicts from run_suite()
    summary      — dict from summarize()
    target_name  — string (e.g. "ollama/llama3")
    output_path  — where to write the .md file

Returns the output path.
"""

from datetime import datetime, timezone


# ──────────────────────────────────────────────────────────────────────
# Verdict metadata
# ──────────────────────────────────────────────────────────────────────

VERDICT_META = {
    "vulnerable":  {"label": "VULNERABLE",  "emoji": "🔴", "rank": 0},
    "uncertain":   {"label": "UNCERTAIN",   "emoji": "🟡", "rank": 1},
    "likely_safe": {"label": "LIKELY SAFE", "emoji": "🟢", "rank": 2},
    "error":       {"label": "ERROR",       "emoji": "⚪", "rank": 3},
}


def _escape_md(text):
    """Escape Markdown-special characters that could break formatting."""
    if text is None:
        return ""
    s = str(text)
    # Only escape characters that would break the current line's structure.
    # We're being conservative — don't escape everything, just the basics.
    s = s.replace("|", "\\|")
    return s


def _truncate(text, n):
    if text is None:
        return ""
    s = str(text)
    if len(s) <= n:
        return s
    return s[:n] + " …[truncated]"


def _code_block(text, lang=""):
    """Wrap text in a fenced code block. Picks a fence long enough not to be
    broken by backticks inside the content."""
    if text is None or text == "":
        return "_(empty)_"
    s = str(text)
    # Choose fence length that avoids collision with content backticks
    fence = "```"
    while fence in s:
        fence += "`"
    return f"{fence}{lang}\n{s}\n{fence}"


# ──────────────────────────────────────────────────────────────────────
# Main writer
# ──────────────────────────────────────────────────────────────────────

def write_markdown_report(results, summary, target_name, output_path):
    """Write a Markdown report. Returns the output path."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = []
    w = lines.append

    # ── Header ──
    w("# ⚔ DIVYASTRA — Prompt Injection Vulnerability Report")
    w("")
    w(f"**Target:** `{target_name}`  ")
    w(f"**Generated:** {generated}  ")
    w(f"**Tool:** DIVYASTRA v2.0.0  ")
    w(f"**Total Payloads:** {summary['total']}")
    w("")
    w("---")
    w("")

    # ── Summary table ──
    w("## Summary")
    w("")
    w("| Verdict | Count |")
    w("|---|---|")
    w(f"| 🔴 Vulnerable  | **{summary['vulnerable']}** |")
    w(f"| 🟡 Uncertain   | {summary['uncertain']} |")
    w(f"| 🟢 Likely Safe | {summary['likely_safe']} |")
    w(f"| ⚪ Errors      | {summary['error']} |")
    w(f"| **Total**      | **{summary['total']}** |")
    w("")
    w("---")
    w("")

    # ── Group results ──
    by_verdict = {"vulnerable": [], "uncertain": [], "likely_safe": [], "error": []}
    for r in results:
        by_verdict.setdefault(r["verdict"], []).append(r)

    for verdict in ("vulnerable", "uncertain", "likely_safe", "error"):
        group = by_verdict.get(verdict, [])
        if not group:
            continue

        meta = VERDICT_META[verdict]
        w(f"## {meta['emoji']} {meta['label']} — {len(group)} finding{'s' if len(group) != 1 else ''}")
        w("")

        for r in group:
            w(f"### `{r['id']}` — {r['category']}")
            w("")
            w(f"**Confidence:** `{r.get('confidence', 0.0):.2f}`  ")
            w(f"**Elapsed:** `{r.get('elapsed_seconds', 0)}s`")
            w("")
            w("**Payload**")
            w("")
            w(_code_block(_truncate(r.get("payload_text", ""), 500)))
            w("")
            w("**Response**")
            w("")
            w(_code_block(_truncate(r.get("response_text", ""), 800) or "(empty)"))
            w("")
            w("**Detection signals**")
            w("")
            reasons = r.get("reasons", [])
            if reasons:
                for reason in reasons:
                    w(f"- {_escape_md(reason)}")
            else:
                w("- _(none)_")
            w("")

        w("---")
        w("")

    # ── Footer ──
    w("_Generated by [DIVYASTRA](https://github.com/CalculusGuy/DIVYASTRA) — "
      "The Divine Weapon for AI Security._")
    w("")
    w("_Author: Nilanjan Chowdhury_")

    content = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path
